extern const int PONE;
extern const int ROOK;
extern const int NIGHT;
extern const int BISHOP;
extern const int QUEEN;
extern const int KING;
extern const int NONE;
extern const int PLAYER_A;
extern const int PLAYER_B;
